### ISSUE TITLE
Handle infinite loops somehow

### ISSUE THREAD

**Issue by vjeux** [bringking/react-run#1]
The lack of run button seems great for a fast developer experience. Unfortunately the big issue with this is that you can end up in an infinite loop very quickly. The typical case is that you start writing the following

``` javascript
while (true) {

}
```

and are about to start writing your inner condition, but at this point auto-run kicks in and triggers an infinite loop. It locks up the tab, you lose all the progress you've made (I've lost 2 hours of work because of that one day) and are super frustrated.

Sadly, I'm not really sure of a good solution :(

**Comment by bringking** [comment]
We could do a couple of things. We can turn auto-run on behind a checkbox, and then use something like this https://github.com/jsbin/loop-protect to warn users of potential infinite loops

**Comment by bringking** [comment]
@vjeux this is now live. I will work on true loop protection soon as well. I will leave this issue open until there is some protection against loops. 

![screen shot 2016-01-17 at 1 10 31 pm](https://cloud.githubusercontent.com/assets/864845/12379655/b74d6de6-bd1b-11e5-86d0-2fba805e0396.png)

**Comment by bringking** [comment]
@vjeux full loop protection now implemented. Closing this issue. See this PR for details. https://github.com/RinconStrategies/react-run/pull/19
