### ISSUE TITLE
Red box is jarring and lacks context

### ISSUE THREAD

**Issue by vjeux** [bringking/react-run#2]
As I'm typing code, I often end up in a state where it doesn't run correctly. But the experience is really jarring as the entire window moves, I lose context on the visual thing I was changing.

Also, the redbox is very uninformative, it says the error message but doesn't have a stack trace nor line number.

![](http://g.recordit.co/ugiHc3VaHw.gif)

Suggestion:
- Overlay the error on-top of the ui, the same way the redbox works on react native
- Display the stack trace, not only the error message
- Display the error in the console as well

For it to work great, I would recommend removing run on edit and instead add a reload button. Otherwise you're going to keep having red boxes as you are typing code.

**Comment by bringking** [comment]
Thanks @vjeux, I agree about the lack of context. We do show the line numbers for "build" errors that we get from Babel, but the runtime frame errors need to be handled better. What version of Chrome are you using? The error bar for me is under the toolbar. 

![screen shot 2016-01-17 at 8 10 04 am](https://cloud.githubusercontent.com/assets/864845/12378120/c1b95148-bcf1-11e5-8776-c851454276f3.png)

**Comment by bringking** [comment]
https://github.com/RinconStrategies/react-run/pull/19 Addresses this finally and covers the output similar to react native.
