### ISSUE TITLE
Enhancement: Minimize redirects

### ISSUE THREAD

**Issue by bringking** [bringking/react-run#20]
Minimize application redirects by -
- [ ] Loading an editor in an "unsaved" state on the initial page view
- [ ] On, the first "save", redirect to the save code page at revision 1

**Comment by nancygomezhd** [comment]
Hello

I am getting more serious redirect errors  http://i.imgur.com/Qavl39I.png

How to solve them? I am operating [free movie downloads](http://moviesgraphy.com/) website.Searched all over the web for solution.

Thanks
